name: pytorch-py3p6-env3
channels: 
  - conda-forge
  - ioam
  - soumith
  - pytorch
dependencies:
  - python=3.7.6
  - keras-gpu
  - pillow
  - numpy
  - mkl
  - holoviews
  - jupyter
  - pandas
  - matplotlib
  - seaborn
  - opencv=4.1.1
  - pytorch=1.5.0
  - torchvision=0.6.0
  - cudatoolkit=10.2
  - cudnn=7.6.5
  - opencv
  - scikit-image
  - pip
  - pip:
    - tqdm
    - pillow
    - packaging
    - appdirs
    - holoviews
    - gpustat
    - sklearn
    - facenet-pytorch
    - opencv-python==3.4.2.16
    - opencv-contrib-python==3.4.2.16
    - gcsfs
    - pytorch-fid